import { redirect, notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { getUser } from "@/lib/auth";
import { getSale } from "@/lib/queries";
import { money, date } from "@/lib/format";
import PrintButton from "@/components/PrintButton";
import s from "@/components/shared.module.css";
import r from "./receipt.module.css";

export default async function ReceiptPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await getUser();
  if (!user) redirect("/login");
  const { id } = await params;
  const sale = await getSale(Number(id));
  if (!sale) notFound();

  return (
    <div className={s.page}>
      <div className={r.actions}>
        <Link className={s.btn} href="/items"><ArrowLeft size={15} /> Back to items</Link>
        <PrintButton />
      </div>

      <div className={r.sheet}>
        <div className={r.top}>
          <div>
            <div className={r.company}>{sale.company}</div>
            <div className={r.tag}>Sales receipt</div>
          </div>
          <div className={r.rcpt}>
            <div className={r.rcptLabel}>Receipt</div>
            <div className={r.rcptCode}>{sale.code}</div>
          </div>
        </div>

        <div className={r.meta}>
          <span className={r.k}>Date</span>
          <span className={r.v}>{date(sale.createdAt)}</span>
          <span className={r.k}>Customer</span>
          <span className={r.v}>{sale.customerName}</span>
          <span className={r.k}>Issued by</span>
          <span className={r.v}>{sale.createdBy ?? "—"}</span>
        </div>

        <table className={r.lineTable}>
          <thead>
            <tr><th>Item</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr>
          </thead>
          <tbody>
            {sale.lines.map((l, i) => (
              <tr key={i}>
                <td>{l.itemName}</td>
                <td>{l.quantity}</td>
                <td>{money(l.unitPrice)}</td>
                <td>{money(l.lineTotal)}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className={r.totalRow}>
          <span>Total</span>
          <span>{money(sale.total)}</span>
        </div>

        <p className={r.foot}>Thank you for your business · Generated by StockLens</p>
      </div>
    </div>
  );
}
